// apps/shell-react/src/App.tsx
import { getMockKycStatus } from '@mfe/mock-api';

export default function App() {
  const status = getMockKycStatus('user-001');

  return (
    <main style={{ fontFamily: 'sans-serif', padding: '2rem' }}>
      <h1>Shell (React)</h1>
      <p>Micro frontend host application</p>
      <p>
        Sample KYC status: <strong>{status.status}</strong>
      </p>
    </main>
  );
}

// apps/kyc-vue/src/App.vue
<script setup lang="ts">
import { getMockKycStatus } from '@mfe/mock-api';

const status = getMockKycStatus('user-002');
</script>

<template>
  <main style="font-family: sans-serif; padding: 2rem">
    <h1>KYC (Vue 3)</h1>
    <p>Micro frontend remote application</p>
    <p>
      Sample KYC status:
      <strong>{{ status.status }}</strong>
    </p>
  </main>
</template>
